# Generated by Django 6.0.2 on 2026-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_dob_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger'), ('admin', 'Admin')], max_length=10),
        ),
    ]
