# Generated by Django 6.0.2 on 2026-03-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in km')),
                ('destination', models.ForeignKey(help_text='Destination Node', on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='core.node')),
                ('source', models.ForeignKey(help_text='Source Node', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='core.node')),
            ],
            options={
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
