server {
    listen 80;
    server_name ishankumar.me www.ishankumar.me;
    return 301 https://$host$request_uri; # redirects all port:80 unencrypted requests to port:443 ssl
    # 301 is permanent redirect
}

server {
    listen 443 ssl; 
    server_name ishankumar.me www.ishankumar.me;

    ssl_certificate /etc/letsencrypt/live/ishankumar.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ishankumar.me/privkey.pem;

    client_max_body_size 10M;

    location /static/ {
        alias /app/static/;
        expires 30d;
    }

    location / {
        proxy_pass http://web:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}