# Generated by Django 6.0.2 on 2026-03-17 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('max_passengers', models.IntegerField(help_text='Maximum passengners allowed on trip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_node', to='core.node')),
                ('driver', models.ForeignKey(blank=True, help_text='Driver of the trip', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_driver', to=settings.AUTH_USER_MODEL)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_node', to='core.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_node', to='core.node')),
            ],
        ),
        migrations.CreateModel(
            name='TripPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_status', models.CharField(choices=[('pending', 'Pending'), ('boarded', 'Boarded'), ('no_show', 'No Show'), ('dropped', 'Dropped Off')], default='pending', max_length=12)),
                ('fare', models.FloatField(blank=True, null=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.node')),
                ('passenger', models.ForeignKey(limit_choices_to={'role': 'passenger'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.node')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
            options={
                'unique_together': {('trip', 'passenger')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(help_text='Users (role: Passenger) onboard trip', related_name='trip_passengers', through='trips.TripPassenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TripNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.node')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('trip', 'order')},
            },
        ),
    ]
