# Generated by Django 6.0.2 on 2026-03-18 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_current_node', to='core.node'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_end_node', to='core.node'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='max_passengers',
            field=models.PositiveIntegerField(help_text='Maximum passengners allowed on trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_start_node', to='core.node'),
        ),
        migrations.CreateModel(
            name='CarPoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('cancelled', 'Cancelled')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.node')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.node')),
            ],
        ),
        migrations.CreateModel(
            name='DriverOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.FloatField()),
                ('detour', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')])),
                ('carpool_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.carpoolrequest')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
